MIgrate to Swift 4
feedhenry-templates/blank-ios-swift pull request #29
Opened 2017-10-17 17:16 UTC by danielpassos

2017-10-18 10:47 UTC, jcesarmobile commented on Podfile
> +	pod 'FeedHenry', '6.0.0'
On the Objective-C ones we have `~>`, so I'm using it on the Swift ones too

2017-10-18 10:50 UTC, jcesarmobile commented
I've added a comment. 
Also, can you update the README.md with the new SDK version, Xcode version and some other changes like the title (it says `blank-ios-app` but this is the swift one), the feedhenry link to the config no longer works, the new one is https://access.redhat.com/documentation/en-us/red_hat_mobile_application_platform_hosted/3/html/client_sdk/native-ios-swift, and some other things you might see.

2017-10-18 11:54 UTC, danielpassos commented
@jcesarmobile Done, can you double check?!

2017-10-18 16:13 UTC, jcesarmobile requested changes
A few more changes

2017-10-18 16:13 UTC, jcesarmobile commented on README.md
>  # blank-ios-app
Title should be blank-ios-swift

2017-10-18 16:13 UTC, jcesarmobile commented on README.md
> +Prerequisites: fh-ios-swift-sdk: 5+, Xcode: 9+, iOS SDK: iOS 9+, CocoaPods: 1.3.0+
fh-ios-swift-sdk should be 6+

2017-10-18 16:15 UTC, jcesarmobile requested changes
Added a few comments

2017-10-18 18:14 UTC, danielpassos commented on README.md
> +Prerequisites: fh-ios-swift-sdk: 5+, Xcode: 9+, iOS SDK: iOS 9+, CocoaPods: 1.3.0+
Done!

2017-10-18 18:14 UTC, danielpassos commented on README.md
>  # blank-ios-app
Done!

2017-10-19 08:09 UTC, jcesarmobile approved these changes
LGTM

2017-10-19 08:09 UTC, merged